{% set version = "0.36.7" %}

package:
  name: sqlalchemy-utils
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/S/SQLAlchemy-Utils/SQLAlchemy-Utils-{{ version }}.tar.gz
  sha256: be319a16022b6a01e1d6c838340485beb4d34fd9c1c19d2303356804fa0faa09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - sqlalchemy >=1.0
    # extras
    - anyjson >=0.3.3
    - babel >=1.3
    - arrow >=0.3.4
    - intervals >=0.7.1
    - phonenumbers >=5.9.2
    - passlib >=1.6,<2.0
    - colour >=0.0.4
    - python-dateutil
    - furl >=0.4.1
    - cryptography >=0.6

test:
  imports:
    - sqlalchemy_utils
    - sqlalchemy_utils.functions
    - sqlalchemy_utils.primitives
    - sqlalchemy_utils.relationships
    - sqlalchemy_utils.types

about:
  home: https://github.com/kvesteri/sqlalchemy-utils
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Various utility functions for SQLAlchemy
  dev_url: https://github.com/kvesteri/sqlalchemy-utils
  doc_url: https://sqlalchemy-utils.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - lvoliveira
    - igortg
